annotation_files:
- Labels-cameras.json
- Labels-v2.json
- Labels-caption.json
input_base_dir: D:/projects/train
processing_params:
  audio_post: 20
  audio_pre: 10
  frame_interval: 2
  min_duration: 10
  seconds_per_segment: 60
storage_params:
  output_base_dir: F:/video_classification
  save_dir_prefix: chunk
video_extensions:
- .mkv
- .mp4
video_names:
- 1_224p.mkv
- 2_224p.mkv
